blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>', views.detail, name='detail'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path,include
from portfolio import views

app_name='portfolio'

urlpatterns = [
    path('', views.home, name='home'),
]

private_blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [

    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=100)
    date = models.DateField(auto_now=True)
    text = models.TextField()

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)

    image = models.ImageField(upload_to='portfolio/images')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404

from .models import Blog
# Create your views here.
def all_blogs(request):
    blogs = Blog.objects.order_by('-date')
    total = len(blogs)
    return render(request, 'blog/all_blog.html', {'blogs': blogs, 'total':total})

def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    blogs = Blog.objects.order_by('-date')

    blog_index = 0
    for index, current in enumerate(blogs):
        if current == blog:
            blog_index = index
            break

    next_index = min(blog_index+1,len(blogs)-1)
    prev_index = max(blog_index-1,0)

    prev = blogs[prev_index].id
    nxt = blogs[next_index].id

    second_next_index = min(next_index+1,len(blogs)-1)
    second_prev_index = max(prev_index-1,0)

    second_next = blogs[second_next_index].id
    second_prev = blogs[second_prev_index].id

    return render(request, 'blog/detail.html',
                  {'blog':blog,'id':blog_id, 'prev':prev, 'next':nxt, 'curr':blog_index+1,'next_index':next_index+1,
                   'prev_index':prev_index+1, 'second_next':second_next,'second_prev':second_prev,
                   'second_next_index':second_next_index+1, 'second_prev_index':second_prev_index+1})

portfolio/views.py
from django.shortcuts import render
from .models import Project
# Create your views here.
def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects':projects})

blog/templates/blog/all_blog.html
{% extends 'portfolio/base.html' %}
{% block content %}
<br><br>
<h1 class="text-center">Welcome to my Blog!</h1>

<div class="container">
{% for blog in blogs %}
    <div class="card text-center">
        <div class="card-header text-muted">
            <span>{{forloop.counter}} / {{blogs.count}}</span>
        </div>
        <div class="card-body text-center">
            <h5 class="card-title"><h3> {{blog.title}} </h3></h5>
            <p class="card-text">{{blog.text|truncatechars:50}}</p>
            <a href="{% url 'blog:detail' blog.id %}" class="btn btn-primary">Detail</a>
        </div>
        <div class="card-footer text-muted text-center">
            <span><time datetime="PTD"> {{blog.date|date:'y. m. d. '}} </time></span>
        </div>
    </div>
<br>
{% endfor %}
</div>

<p> scroller, infinite scroll</p>
{% endblock %}

blog/templates/blog/detail.html
{% extends 'portfolio/base.html' %}
{% block content %}
{% load static %}
<link href="{% static 'blog/blog.css' %}" rel="stylesheet" type="text/css">
<br><br>
<div class="container">
    <h3 class="text-center">{{blog.title}}</h3>
    <div class="text-center">
        <time>{{blog.date|date:'y. m. d.'}}</time>
        <div>
            <a href="{% url 'blog:all_blogs' %}"><img src="{% static 'blog/arrow-left.svg' %}"></a>
        </div>
    </div>
    <br>
    <div class="blog-text">
        <p class="">{{blog.text|safe|linebreaks}}</p>
    </div>
    <br>
    <div class="nav-center">
        <nav aria-label="Page navigation example">
          <ul class="pagination">
          {% if prev_index != second_prev_index %}
            <li class="page-item"><a class="page-link" href="{% url 'blog:detail' second_prev %}">{{second_prev_index}}</a></li>
          {% endif %}
          {% if prev_index != curr %}
            <li class="page-item"><a class="page-link" href="{% url 'blog:detail' prev %}">{{prev_index}}</a></li>
          {% endif %}
            <li class="page-item active"><a class="page-link" href="#">{{curr}}</a></li>
          {% if next_index != curr %}
            <li class="page-item"><a class="page-link" href="{% url 'blog:detail' next %}">{{next_index}}</a></li>
          {% endif %}
          {% if next_index != second_next_index %}
            <li class="page-item"><a class="page-link" href="{% url 'blog:detail' second_next %}">{{second_next_index}}</a></li>
          {% endif %}
          </ul>
        </nav>
    </div>
</div>
{% endblock %}

portfolio/templates/portfolio/base.html
{% load static %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

<!doctype html>
<html lang="en">
    <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link href="{% static 'portfolio/base.css' %}" rel="stylesheet" type="text/css">

    <title>Minki's Portfolio</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-sm navbar-light bg-light">
            <div class="d-flex justify-content-between w-100 container">
                <div class="d-flex" id="menus">
                    <svg width="40px" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 512 512" style="enable-background:new 0 0 512 512;" xml:space="preserve"><g><g><path d="M511.981,118.509c-0.135-2.956-1.892-5.726-4.565-7.04l-159.24-79.62c-3.776-1.887-8.363-0.64-10.664,2.898 L229.916,200.282l-55.413-85.891c-0.796-1.235-1.945-2.264-3.259-2.922l-159.24-79.62C6.582,29.138,0,33.218,0,39.268v79.621 c0,4.581,3.712,8.294,8.294,8.294c4.581,0,8.294-3.712,8.294-.294V52.687l142.652,71.326v335.32L16.587,388.008V154.277 c0-4.581-3.712-8.294-8.294-8.294c-4.581,0-8.294,3.712-8.294,8.294v238.857c0,3.142,1.775,6.013,4.585,7.418l159.24,79.62  c5.427,2.714,12.003-1.375,12.003-7.418V318.087l324.17,162.085c5.427,2.714,12.003-1.375,12.003-7.418V118.888 C512,118.76,511.987,118.636,511.981,118.509z M175.827,299.541v-152.5l145.239,225.12L175.827,299.541z M495.413,459.335 l-139.34-69.671l108.576-186.993c2.299-3.961,0.952-9.037-3.009-11.337c-3.96-2.298-9.036-0.953-11.337,3.009L344.094,377.258 L239.77,215.555L347.383,49.998l144.717,72.359l-26.387,45.446c-2.299,3.961-0.952,9.037,3.009,11.337  c3.958,2.297,9.035,0.953,11.337-3.009l15.354-26.443V459.335z" fill="#000" /></g></g></svg>
                        <ul class="navbar-nav">
                            <li class="nav-item active">
                            <a class="nav-link menu" href="{% url 'portfolio:home' %}"><img src="{% static 'portfolio/home.svg' %}">Portfolio<span class="sr-only"></span></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link menu" href="{% url 'blog:all_blogs' %}"><img src="{% static 'portfolio/message-square.svg' %}">Blog</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link menu" href="{% static 'portfolio/random_pdf.pdf' %}" target="_blank"><img src="{% static 'portfolio/download.svg' %}">Resume</a>
                            </li>
                        </ul>
                </div>
                <div class="d-flex" id="navbarNav2">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                        <a class="nav-link" href="https://www.linkedin.com/in/minki-kim-219392199/" target="_blank"><img src="{% static 'portfolio/linkedin.svg' %}"> <span class="sr-only"></span></a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" href="https://github.com/wer153" target="_blank"><img src="{% static 'portfolio/github.svg' %}"></a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" href="mailto:77wer153@gmail.com"><img src="{% static 'portfolio/mail.svg' %}"></a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        {% block content %}{% endblock %}

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    </body>
</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}


{% block content %}


<!--{% load static %}-->
<br>
<div class="text-center">
    <img class=".img-fluid" src="{% static 'portfolio/king.png' %}" width="40%"/>
</div>

<br>

<div class="container">
    <div class="row">
        {% for project in projects%}
        <div class="col-md-4">
            <h3 class="text-center">{{ project.title }}</h3>
            <p>{{ project.description }}</p>
            <img class=".img-fluid" src={{ project.image.url }} width="100%"">
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}